
files.sources <- paste("r_files",list.files("r_files"),sep="/")
sapply(files.sources, source)
library(shinyWidgets)
library(shinyFiles)
library(DT)
library(plotly)
library(tictoc)
  
library(shinythemes)
library(dashboardthemes)
library(shinyFiles)
library(shinyWidgets)
library(shinyjs)
library(RcppRoll)
library(shinydashboard)
library(colourpicker)
library(webshot)
library(corrr)
library(sortable)
library(data.table)
library(dplyr)
library(tidyr)
library(tidyverse)
library(caTools)
library(stats)
library(stringr)
library(scales)
library(gtools)
library(gmodels)
library(outliers)
library(spant)
library(correlation)
library(zoo)
library(ggplot2)
library(ggfortify)
library(plotly)
library(viridis)
library(cvms) 
library(grid)
library(gridExtra)
library(yardstick)
library(GGally)
library(fields)
library(RColorBrewer)
library(ggtern) 
library(factoextra)
library(cluster)
library(mclust)
library(FactoMineR)
library(randomForest)
library(caret)
library(corrplot)
library(ggcorrplot)
library(ggnewscale)
library(imagine)
library(tictoc)
library(EnvStats)

global_vars <- function(){readRDS('global_variables.Rds')}
